//# Using gestures <a title="View raw file" href="https://raw.github.com/gameclosure/examples/master/src/events/input-gesture/src/Application.js"><img src="../../include/download_icon.png" class="icon"></a>
//This example shows how to use the Pinch, Rotate, Drag, and Swipe events generated by the GestureView.

import device;
import ui.View as View;
import ui.TextView as TextView;
import ui.GestureView as GestureView;

//## Class: Application
//Create an Application.
exports = Class(GC.Application, function () {
	this.initUI = function () {
		// Create a GestureView
		var gview = new GestureView({
			superview: this.view,
			layout: 'box',
			backgroundColor: 'blue'
		});
		// Subscribe to gesture events: Pinch, Rotate, Drag, Swipe
		gview.on('Pinch', bind(this, 'pinch'));
		gview.on('Rotate', bind(this, 'rotate'));
		gview.on('Drag', bind(this, 'drag'));
		gview.on('Swipe', bind(this, 'swipe'));
		// This view scales, rotates, and moves around
		// in response to Pinch, Rotate, and Drag events
		this.demoView = new View({
			superview: this.view,
			width: 100,
			height: 100,
			x: 100,
			y: 200,
			canHandleEvents: false,
			blockEvents: true,
			backgroundColor: 'red'
		});
		// This view logs Swipe events
		this.logView = new TextView({
			superview: this.view,
			layout: 'box',
			bottom: 0,
			height: 50,
			canHandleEvents: false,
			blockEvents: true,
			backgroundColor: 'green',
			text: device.isSimulator ? 'test on device for multitouch' : 'pinch, rotate, drag, swipe'
		});
	};

	this.pinch = function (d) {
		// scale demoView in response to Pinch event
		this.demoView.style.scale = d;
	};

	this.rotate = function (r) {
		// rotate demoView in response to Rotate event
		this.demoView.style.r = r;
	};

	this.drag = function(startEvent, endEvent, delta) {
		// reposition demoView in response to Drag event
		this.demoView.style.x += delta.x;
		this.demoView.style.y += delta.y;
	};

	this.swipe = function (dir) {
		// update logView in response to Swipe event
		this.logView.setText(dir);
	};
});

//The output should look like this screenshot:
//<img src="./doc/screenshot.png" alt="a book screenshot" class="screenshot">